insert into authors (id, first_name, last_name) values (1, 'Roselin', 'Varsey');
insert into authors (id, first_name, last_name) values (2, 'Rex', 'Kerin');
insert into authors (id, first_name, last_name) values (3, 'Casar', 'Hanlin');
insert into authors (id, first_name, last_name) values (4, 'Adelaida', 'Eynald');
insert into authors (id, first_name, last_name) values (5, 'Roxanna', 'Copnar');
insert into authors (id, first_name, last_name) values (6, 'Camel', 'Clawley');
insert into authors (id, first_name, last_name) values (7, 'Denyse', 'Fussey');
insert into authors (id, first_name, last_name) values (8, 'Stevy', 'Clendening');
insert into authors (id, first_name, last_name) values (9, 'Cecilio', 'Handrik');
insert into authors (id, first_name, last_name) values (10, 'Dov', 'Amott');
insert into authors (id, first_name, last_name) values (11, 'Erick', 'Gartshore');
insert into authors (id, first_name, last_name) values (12, 'Bradan', 'Lamburn');
insert into authors (id, first_name, last_name) values (13, 'Guss', 'Deex');
insert into authors (id, first_name, last_name) values (14, 'Sam', 'Bowich');
insert into authors (id, first_name, last_name) values (15, 'Chrysler', 'Cowing');
insert into authors (id, first_name, last_name) values (16, 'Darci', 'Noni');
insert into authors (id, first_name, last_name) values (17, 'Kaylil', 'Purdey');
insert into authors (id, first_name, last_name) values (18, 'Percival', 'Ganter');
insert into authors (id, first_name, last_name) values (19, 'Bernie', 'Hoodlass');
insert into authors (id, first_name, last_name) values (20, 'Menard', 'Jonah');
insert into authors (id, first_name, last_name) values (21, 'Gregorius', 'Petran');
insert into authors (id, first_name, last_name) values (22, 'Erna', 'Loisi');
insert into authors (id, first_name, last_name) values (23, 'Dina', 'Hymers');
insert into authors (id, first_name, last_name) values (24, 'Buddy', 'Leggatt');
insert into authors (id, first_name, last_name) values (25, 'Carmela', 'Vinck');
insert into authors (id, first_name, last_name) values (26, 'Tarrah', 'Shaughnessy');
insert into authors (id, first_name, last_name) values (27, 'Temple', 'Ankrett');
insert into authors (id, first_name, last_name) values (28, 'Ferdinande', 'Bullough');
insert into authors (id, first_name, last_name) values (29, 'Ofilia', 'Edleston');
insert into authors (id, first_name, last_name) values (30, 'Terry', 'Pering');
insert into authors (id, first_name, last_name) values (31, 'Brnaba', 'Wooddisse');
insert into authors (id, first_name, last_name) values (32, 'Pegeen', 'Dewdney');
insert into authors (id, first_name, last_name) values (33, 'Sarene', 'Playhill');
insert into authors (id, first_name, last_name) values (34, 'De', 'Penke');
insert into authors (id, first_name, last_name) values (35, 'Ransell', 'Authers');
insert into authors (id, first_name, last_name) values (36, 'Annice', 'McGuggy');
insert into authors (id, first_name, last_name) values (37, 'Wandis', 'Banisch');
insert into authors (id, first_name, last_name) values (38, 'Walton', 'MacNamara');
insert into authors (id, first_name, last_name) values (39, 'Alf', 'Bust');
insert into authors (id, first_name, last_name) values (40, 'Corty', 'Douch');
insert into authors (id, first_name, last_name) values (41, 'Janice', 'Joyner');
insert into authors (id, first_name, last_name) values (42, 'Neall', 'Sandbatch');
insert into authors (id, first_name, last_name) values (43, 'Sandi', 'Praill');
insert into authors (id, first_name, last_name) values (44, 'Towny', 'Cleverly');
insert into authors (id, first_name, last_name) values (45, 'Hardy', 'Bowkley');
insert into authors (id, first_name, last_name) values (46, 'Rickey', 'Speariett');
insert into authors (id, first_name, last_name) values (47, 'Brewster', 'Starking');
insert into authors (id, first_name, last_name) values (48, 'Vin', 'Furmenger');
insert into authors (id, first_name, last_name) values (49, 'Winn', 'Schruur');
insert into authors (id, first_name, last_name) values (50, 'Weber', 'Boxen');
insert into authors (id, first_name, last_name) values (51, 'Alikee', 'Skough');
insert into authors (id, first_name, last_name) values (52, 'Jorrie', 'Utridge');
insert into authors (id, first_name, last_name) values (53, 'Phil', 'Heads');
insert into authors (id, first_name, last_name) values (54, 'Enriqueta', 'Rome');
insert into authors (id, first_name, last_name) values (55, 'Stacia', 'Sarchwell');
insert into authors (id, first_name, last_name) values (56, 'Bjorn', 'Urrey');
insert into authors (id, first_name, last_name) values (57, 'Lenci', 'Narracott');
insert into authors (id, first_name, last_name) values (58, 'Bogart', 'Rummery');
insert into authors (id, first_name, last_name) values (59, 'Britni', 'Sedge');
insert into authors (id, first_name, last_name) values (60, 'Ileane', 'Groucock');
insert into authors (id, first_name, last_name) values (61, 'Nathanial', 'Pidler');
insert into authors (id, first_name, last_name) values (62, 'Shelbi', 'Gurg');
insert into authors (id, first_name, last_name) values (63, 'Domenic', 'Ganley');
insert into authors (id, first_name, last_name) values (64, 'Ruben', 'Lamanby');
insert into authors (id, first_name, last_name) values (65, 'Sauncho', 'Rizziello');
insert into authors (id, first_name, last_name) values (66, 'Stanislaw', 'Burril');
insert into authors (id, first_name, last_name) values (67, 'Dorisa', 'Corsan');
insert into authors (id, first_name, last_name) values (68, 'Adaline', 'Scholcroft');
insert into authors (id, first_name, last_name) values (69, 'Elyssa', 'Strathearn');
insert into authors (id, first_name, last_name) values (70, 'Peg', 'Siddon');
insert into authors (id, first_name, last_name) values (71, 'Orbadiah', 'Gravie');
insert into authors (id, first_name, last_name) values (72, 'Franni', 'Rase');
insert into authors (id, first_name, last_name) values (73, 'Devland', 'Cullen');
insert into authors (id, first_name, last_name) values (74, 'Georges', 'Lyddiatt');
insert into authors (id, first_name, last_name) values (75, 'Waldon', 'Stonebridge');
insert into authors (id, first_name, last_name) values (76, 'Elia', 'Leddie');
insert into authors (id, first_name, last_name) values (77, 'Nial', 'Emmett');
insert into authors (id, first_name, last_name) values (78, 'Lyndsey', 'Rosenbloom');
insert into authors (id, first_name, last_name) values (79, 'Annissa', 'Gurner');
insert into authors (id, first_name, last_name) values (80, 'Justina', 'Hundall');
insert into authors (id, first_name, last_name) values (81, 'Ninon', 'Murrey');
insert into authors (id, first_name, last_name) values (82, 'Lorraine', 'Peverell');
insert into authors (id, first_name, last_name) values (83, 'Taber', 'Pentony');
insert into authors (id, first_name, last_name) values (84, 'Lind', 'D''eathe');
insert into authors (id, first_name, last_name) values (85, 'Artemas', 'Mountain');
insert into authors (id, first_name, last_name) values (86, 'Donella', 'Gipson');
insert into authors (id, first_name, last_name) values (87, 'Alphonse', 'Wyles');
insert into authors (id, first_name, last_name) values (88, 'Judy', 'Epp');
insert into authors (id, first_name, last_name) values (89, 'Tabbie', 'Lochrie');
insert into authors (id, first_name, last_name) values (90, 'Naoma', 'Borzone');
insert into authors (id, first_name, last_name) values (91, 'Joey', 'Marling');
insert into authors (id, first_name, last_name) values (92, 'Libbi', 'Lawles');
insert into authors (id, first_name, last_name) values (93, 'Branden', 'Chaffyn');
insert into authors (id, first_name, last_name) values (94, 'Beau', 'Hudd');
insert into authors (id, first_name, last_name) values (95, 'Dulcy', 'Fretwell');
insert into authors (id, first_name, last_name) values (96, 'Teddy', 'Swadden');
insert into authors (id, first_name, last_name) values (97, 'Ophelie', 'Hasnney');
insert into authors (id, first_name, last_name) values (98, 'Clarine', 'Swalowe');
insert into authors (id, first_name, last_name) values (99, 'Dennet', 'Rhule');
insert into authors (id, first_name, last_name) values (100, 'Kyla', 'Blackboro');

insert into books (id, price, price_old, title, author_id) values (1, 1453, 2819, 'Latlux', 7);
insert into books (id, price, price_old, title, author_id) values (2, 683, 1036, 'Aerified', 4);
insert into books (id, price, price_old, title, author_id) values (3, 2527, 3620, 'Tampflex', 16);
insert into books (id, price, price_old, title, author_id) values (4, 2944, 3761, 'Viva', 19);
insert into books (id, price, price_old, title, author_id) values (5, 969, 1868, 'Cardguard', 18);
insert into books (id, price, price_old, title, author_id) values (6, 891, 3248, 'Rank', 6);
insert into books (id, price, price_old, title, author_id) values (7, 617, 2219, 'Asoka', 11);
insert into books (id, price, price_old, title, author_id) values (8, 2316, 3024, 'Duobam', 5);
insert into books (id, price, price_old, title, author_id) values (9, 1453, 2566, 'Fix San', 4);
insert into books (id, price, price_old, title, author_id) values (10, 1894, 1848, 'Ronstring', 6);
insert into books (id, price, price_old, title, author_id) values (11, 778, 1961, 'Zaam-Dox', 6);
insert into books (id, price, price_old, title, author_id) values (12, 1566, 1674, 'Tampflex', 6);
insert into books (id, price, price_old, title, author_id) values (13, 2656, 2255, 'Alpha', 14);
insert into books (id, price, price_old, title, author_id) values (14, 1004, 1556, 'Cardify', 17);
insert into books (id, price, price_old, title, author_id) values (15, 1881, 2672, 'Tampflex', 18);
insert into books (id, price, price_old, title, author_id) values (16, 2901, 2687, 'Ventosanzap', 7);
insert into books (id, price, price_old, title, author_id) values (17, 617, 2908, 'Zoolab', 2);
insert into books (id, price, price_old, title, author_id) values (18, 2127, 3431, 'Job', 13);
insert into books (id, price, price_old, title, author_id) values (19, 1555, 1265, 'Transcof', 2);
insert into books (id, price, price_old, title, author_id) values (20, 2656, 1751, 'Overhold', 3);
insert into books (id, price, price_old, title, author_id) values (21, 2334, 2177, 'Duobam', 15);